// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ComplexOptional {
    pub data: Option<crate::typesOptionalData>,

    pub items: Vec<crate::typesOptionalItem>,

    pub mapping: std::collections::HashMap<String, Option<crate::typesOptionalValue>>,
}

impl ComplexOptional {
    /// Create a new ComplexOptional instance
    pub fn new(
        data: Option<crate::typesOptionalData>,
        items: Vec<crate::typesOptionalItem>,
        mapping: std::collections::HashMap<String, Option<crate::typesOptionalValue>>,
    ) -> Self {
        Self {
            data,
            items,
            mapping,
        }
    }
}

impl Default for ComplexOptional {
    fn default() -> Self {
        Self::new(None, Vec::new(), std::collections::HashMap::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ComplexOptional {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("data".to_string(), self.data.to_baml_value()?);
        map.insert("items".to_string(), self.items.to_baml_value()?);
        map.insert("mapping".to_string(), self.mapping.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "ComplexOptional".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ComplexOptional {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let data = map
                    .get("data")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'data' in ComplexOptional"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let items = map
                    .get("items")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'items' in ComplexOptional"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mapping = map
                    .get("mapping")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mapping' in ComplexOptional"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(data, items, mapping))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MixedOptionalNullable {
    pub id: i64,

    pub description: Option<String>,

    pub metadata: Option<String>,

    pub notes: Option<String>,

    pub tags: Vec<String>,

    pub categories: Option<Vec<String>>,

    pub keywords: Option<Vec<String>>,

    pub primaryUser: crate::typesUser,

    pub secondaryUser: Option<crate::typesUser>,

    pub tertiaryUser: Option<crate::typesUser>,
}

impl MixedOptionalNullable {
    /// Create a new MixedOptionalNullable instance
    pub fn new(
        id: i64,
        description: Option<String>,
        metadata: Option<String>,
        notes: Option<String>,
        tags: Vec<String>,
        categories: Option<Vec<String>>,
        keywords: Option<Vec<String>>,
        primaryUser: crate::typesUser,
        secondaryUser: Option<crate::typesUser>,
        tertiaryUser: Option<crate::typesUser>,
    ) -> Self {
        Self {
            id,
            description,
            metadata,
            notes,
            tags,
            categories,
            keywords,
            primaryUser,
            secondaryUser,
            tertiaryUser,
        }
    }
}

impl Default for MixedOptionalNullable {
    fn default() -> Self {
        Self::new(
            0,
            None,
            None,
            None,
            Vec::new(),
            None,
            None,
            crate::typesUser::default(),
            None,
            None,
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedOptionalNullable {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("description".to_string(), self.description.to_baml_value()?);
        map.insert("metadata".to_string(), self.metadata.to_baml_value()?);
        map.insert("notes".to_string(), self.notes.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        map.insert("categories".to_string(), self.categories.to_baml_value()?);
        map.insert("keywords".to_string(), self.keywords.to_baml_value()?);
        map.insert("primaryUser".to_string(), self.primaryUser.to_baml_value()?);
        map.insert(
            "secondaryUser".to_string(),
            self.secondaryUser.to_baml_value()?,
        );
        map.insert(
            "tertiaryUser".to_string(),
            self.tertiaryUser.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedOptionalNullable".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedOptionalNullable {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let description = map
                    .get("description")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'description' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let metadata = map
                    .get("metadata")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'metadata' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let notes = map
                    .get("notes")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'notes' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let tags = map
                    .get("tags")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let categories = map
                    .get("categories")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'categories' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let keywords = map
                    .get("keywords")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'keywords' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let primaryUser = map
                    .get("primaryUser")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'primaryUser' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let secondaryUser = map
                    .get("secondaryUser")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'secondaryUser' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let tertiaryUser = map
                    .get("tertiaryUser")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tertiaryUser' in MixedOptionalNullable"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    id,
                    description,
                    metadata,
                    notes,
                    tags,
                    categories,
                    keywords,
                    primaryUser,
                    secondaryUser,
                    tertiaryUser,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NullableTypes {
    pub nullableString: Option<String>,

    pub nullableInt: Option<i64>,

    pub nullableFloat: Option<f64>,

    pub nullableBool: Option<bool>,

    pub nullableArray: Option<Vec<String>>,

    pub nullableObject: Option<crate::typesUser>,
}

impl NullableTypes {
    /// Create a new NullableTypes instance
    pub fn new(
        nullableString: Option<String>,
        nullableInt: Option<i64>,
        nullableFloat: Option<f64>,
        nullableBool: Option<bool>,
        nullableArray: Option<Vec<String>>,
        nullableObject: Option<crate::typesUser>,
    ) -> Self {
        Self {
            nullableString,
            nullableInt,
            nullableFloat,
            nullableBool,
            nullableArray,
            nullableObject,
        }
    }
}

impl Default for NullableTypes {
    fn default() -> Self {
        Self::new(None, None, None, None, None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NullableTypes {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "nullableString".to_string(),
            self.nullableString.to_baml_value()?,
        );
        map.insert("nullableInt".to_string(), self.nullableInt.to_baml_value()?);
        map.insert(
            "nullableFloat".to_string(),
            self.nullableFloat.to_baml_value()?,
        );
        map.insert(
            "nullableBool".to_string(),
            self.nullableBool.to_baml_value()?,
        );
        map.insert(
            "nullableArray".to_string(),
            self.nullableArray.to_baml_value()?,
        );
        map.insert(
            "nullableObject".to_string(),
            self.nullableObject.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "NullableTypes".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NullableTypes {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let nullableString = map
                    .get("nullableString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableString' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableInt = map
                    .get("nullableInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableInt' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableFloat = map
                    .get("nullableFloat")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableFloat' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableBool = map
                    .get("nullableBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableBool' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableArray = map
                    .get("nullableArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableArray' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableObject = map
                    .get("nullableObject")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableObject' in NullableTypes"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    nullableString,
                    nullableInt,
                    nullableFloat,
                    nullableBool,
                    nullableArray,
                    nullableObject,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OptionalData {
    pub value: String,

    pub count: Option<i64>,

    pub enabled: Option<bool>,
}

impl OptionalData {
    /// Create a new OptionalData instance
    pub fn new(value: String, count: Option<i64>, enabled: Option<bool>) -> Self {
        Self {
            value,
            count,
            enabled,
        }
    }
}

impl Default for OptionalData {
    fn default() -> Self {
        Self::new(String::new(), None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalData {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("value".to_string(), self.value.to_baml_value()?);
        map.insert("count".to_string(), self.count.to_baml_value()?);
        map.insert("enabled".to_string(), self.enabled.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalData".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalData {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let value = map
                    .get("value")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'value' in OptionalData"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let count = map
                    .get("count")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'count' in OptionalData"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let enabled = map
                    .get("enabled")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'enabled' in OptionalData"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(value, count, enabled))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OptionalFields {
    pub requiredString: String,

    pub optionalString: Option<String>,

    pub requiredInt: i64,

    pub optionalInt: Option<i64>,

    pub requiredBool: bool,

    pub optionalBool: Option<bool>,

    pub optionalArray: Option<Vec<String>>,

    pub optionalMap: Option<std::collections::HashMap<String, String>>,
}

impl OptionalFields {
    /// Create a new OptionalFields instance
    pub fn new(
        requiredString: String,
        optionalString: Option<String>,
        requiredInt: i64,
        optionalInt: Option<i64>,
        requiredBool: bool,
        optionalBool: Option<bool>,
        optionalArray: Option<Vec<String>>,
        optionalMap: Option<std::collections::HashMap<String, String>>,
    ) -> Self {
        Self {
            requiredString,
            optionalString,
            requiredInt,
            optionalInt,
            requiredBool,
            optionalBool,
            optionalArray,
            optionalMap,
        }
    }
}

impl Default for OptionalFields {
    fn default() -> Self {
        Self::new(String::new(), None, 0, None, false, None, None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalFields {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "requiredString".to_string(),
            self.requiredString.to_baml_value()?,
        );
        map.insert(
            "optionalString".to_string(),
            self.optionalString.to_baml_value()?,
        );
        map.insert("requiredInt".to_string(), self.requiredInt.to_baml_value()?);
        map.insert("optionalInt".to_string(), self.optionalInt.to_baml_value()?);
        map.insert(
            "requiredBool".to_string(),
            self.requiredBool.to_baml_value()?,
        );
        map.insert(
            "optionalBool".to_string(),
            self.optionalBool.to_baml_value()?,
        );
        map.insert(
            "optionalArray".to_string(),
            self.optionalArray.to_baml_value()?,
        );
        map.insert("optionalMap".to_string(), self.optionalMap.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalFields".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalFields {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let requiredString = map
                    .get("requiredString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'requiredString' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalString = map
                    .get("optionalString")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalString' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let requiredInt = map
                    .get("requiredInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'requiredInt' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalInt = map
                    .get("optionalInt")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalInt' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let requiredBool = map
                    .get("requiredBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'requiredBool' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalBool = map
                    .get("optionalBool")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalBool' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalArray = map
                    .get("optionalArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalArray' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalMap = map
                    .get("optionalMap")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalMap' in OptionalFields"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    requiredString,
                    optionalString,
                    requiredInt,
                    optionalInt,
                    requiredBool,
                    optionalBool,
                    optionalArray,
                    optionalMap,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OptionalItem {
    pub id: i64,

    pub name: String,

    pub description: Option<String>,

    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl OptionalItem {
    /// Create a new OptionalItem instance
    pub fn new(
        id: i64,
        name: String,
        description: Option<String>,
        metadata: Option<std::collections::HashMap<String, String>>,
    ) -> Self {
        Self {
            id,
            name,
            description,
            metadata,
        }
    }
}

impl Default for OptionalItem {
    fn default() -> Self {
        Self::new(0, String::new(), None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalItem {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("description".to_string(), self.description.to_baml_value()?);
        map.insert("metadata".to_string(), self.metadata.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalItem".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalItem {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in OptionalItem"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in OptionalItem"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let description = map
                    .get("description")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'description' in OptionalItem"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let metadata = map
                    .get("metadata")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'metadata' in OptionalItem"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, description, metadata))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OptionalValue {
    pub data: Option<crate::typesUnion2IntOrString>,

    pub optional: Option<String>,
}

impl OptionalValue {
    /// Create a new OptionalValue instance
    pub fn new(data: Option<crate::typesUnion2IntOrString>, optional: Option<String>) -> Self {
        Self { data, optional }
    }
}

impl Default for OptionalValue {
    fn default() -> Self {
        Self::new(None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalValue {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("data".to_string(), self.data.to_baml_value()?);
        map.insert("optional".to_string(), self.optional.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalValue".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalValue {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let data = map
                    .get("data")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'data' in OptionalValue"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optional = map
                    .get("optional")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optional' in OptionalValue"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(data, optional))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Product {
    pub id: i64,

    pub name: String,

    pub price: Option<f64>,
}

impl Product {
    /// Create a new Product instance
    pub fn new(id: i64, name: String, price: Option<f64>) -> Self {
        Self { id, name, price }
    }
}

impl Default for Product {
    fn default() -> Self {
        Self::new(0, String::new(), None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Product {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("price".to_string(), self.price.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Product".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Product {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let price = map
                    .get("price")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'price' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, price))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UnionWithNull {
    pub simpleUnion: crate::typesUnion2IntOrString,

    pub nullableUnion: Option<crate::typesUnion2IntOrString>,

    pub optionalUnion: Option<crate::typesUnion2IntOrString>,

    pub complexUnion: Option<crate::typesUnion2ProductOrUser>,
}

impl UnionWithNull {
    /// Create a new UnionWithNull instance
    pub fn new(
        simpleUnion: crate::typesUnion2IntOrString,
        nullableUnion: Option<crate::typesUnion2IntOrString>,
        optionalUnion: Option<crate::typesUnion2IntOrString>,
        complexUnion: Option<crate::typesUnion2ProductOrUser>,
    ) -> Self {
        Self {
            simpleUnion,
            nullableUnion,
            optionalUnion,
            complexUnion,
        }
    }
}

impl Default for UnionWithNull {
    fn default() -> Self {
        Self::new(crate::typesUnion2IntOrString::default(), None, None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for UnionWithNull {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("simpleUnion".to_string(), self.simpleUnion.to_baml_value()?);
        map.insert(
            "nullableUnion".to_string(),
            self.nullableUnion.to_baml_value()?,
        );
        map.insert(
            "optionalUnion".to_string(),
            self.optionalUnion.to_baml_value()?,
        );
        map.insert(
            "complexUnion".to_string(),
            self.complexUnion.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "UnionWithNull".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for UnionWithNull {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let simpleUnion = map
                    .get("simpleUnion")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'simpleUnion' in UnionWithNull"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableUnion = map
                    .get("nullableUnion")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableUnion' in UnionWithNull"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalUnion = map
                    .get("optionalUnion")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalUnion' in UnionWithNull"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let complexUnion = map
                    .get("complexUnion")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'complexUnion' in UnionWithNull"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    simpleUnion,
                    nullableUnion,
                    optionalUnion,
                    complexUnion,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct User {
    pub id: i64,

    pub name: String,

    pub email: Option<String>,

    pub phone: Option<String>,
}

impl User {
    /// Create a new User instance
    pub fn new(id: i64, name: String, email: Option<String>, phone: Option<String>) -> Self {
        Self {
            id,
            name,
            email,
            phone,
        }
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new(0, String::new(), None, None)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for User {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("email".to_string(), self.email.to_baml_value()?);
        map.insert("phone".to_string(), self.phone.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "User".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for User {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let email = map
                    .get("email")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'email' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let phone = map
                    .get("phone")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'phone' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, email, phone))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union2IntOrString {
    String(String),
    Int(i64),
}

impl Union2IntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2IntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2IntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }
}

/// Pattern matching helper for Union2IntOrString
impl Union2IntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union2IntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union2IntOrString {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::String(v) => v.to_baml_value(),
            Self::Int(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union2IntOrString {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try String variant
        if let Ok(variant_value) = String::from_baml_value(value.clone()) {
            return Ok(Self::String(variant_value));
        }
        // Try Int variant
        if let Ok(variant_value) = i64::from_baml_value(value.clone()) {
            return Ok(Self::Int(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union2IntOrString",
            value
        )))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union2ProductOrUser {
    User(crate::typesUser),
    Product(crate::typesProduct),
}

impl Union2ProductOrUser {
    /// Check if this union is a User variant
    pub fn is_user(&self) -> bool {
        matches!(self, Self::User(_))
    }
    /// Get the User value if this union contains it
    pub fn as_user(&self) -> Option<&crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the User value, consuming the union
    pub fn into_user(self) -> Option<crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the User value if this union contains it
    pub fn as_user_mut(&mut self) -> Option<&mut crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2ProductOrUser with a User variant
    pub fn user(value: crate::typesUser) -> Self {
        Self::User(value)
    }

    /// Check if this union is a Product variant
    pub fn is_product(&self) -> bool {
        matches!(self, Self::Product(_))
    }
    /// Get the Product value if this union contains it
    pub fn as_product(&self) -> Option<&crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Product value, consuming the union
    pub fn into_product(self) -> Option<crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Product value if this union contains it
    pub fn as_product_mut(&mut self) -> Option<&mut crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union2ProductOrUser with a Product variant
    pub fn product(value: crate::typesProduct) -> Self {
        Self::Product(value)
    }
}

/// Pattern matching helper for Union2ProductOrUser
impl Union2ProductOrUser {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        user: impl FnOnce(&crate::typesUser) -> T,
        product: impl FnOnce(&crate::typesProduct) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        user: impl FnOnce(crate::typesUser) -> T,
        product: impl FnOnce(crate::typesProduct) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union2ProductOrUser {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::User(v) => write!(f, "User({:?})", v),
            Self::Product(v) => write!(f, "Product({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union2ProductOrUser {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::User(v) => v.to_baml_value(),
            Self::Product(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union2ProductOrUser {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try User variant
        if let Ok(variant_value) = crate::typesUser::from_baml_value(value.clone()) {
            return Ok(Self::User(variant_value));
        }
        // Try Product variant
        if let Ok(variant_value) = crate::typesProduct::from_baml_value(value.clone()) {
            return Ok(Self::Product(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union2ProductOrUser",
            value
        )))
    }
}
