// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MediaAnalysisResult {
    pub topics: Vec<String>,

    pub analysisText: String,
}

impl MediaAnalysisResult {
    /// Create a new MediaAnalysisResult instance
    pub fn new(topics: Vec<String>, analysisText: String) -> Self {
        Self {
            topics,
            analysisText,
        }
    }
}

impl Default for MediaAnalysisResult {
    fn default() -> Self {
        Self::new(Vec::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MediaAnalysisResult {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("topics".to_string(), self.topics.to_baml_value()?);
        map.insert(
            "analysisText".to_string(),
            self.analysisText.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MediaAnalysisResult".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MediaAnalysisResult {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let topics = map
                    .get("topics")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'topics' in MediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let analysisText = map
                    .get("analysisText")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'analysisText' in MediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(topics, analysisText))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MediaArrayAnalysisResult {
    pub analysisText: String,

    pub mediaCount: i64,
}

impl MediaArrayAnalysisResult {
    /// Create a new MediaArrayAnalysisResult instance
    pub fn new(analysisText: String, mediaCount: i64) -> Self {
        Self {
            analysisText,
            mediaCount,
        }
    }
}

impl Default for MediaArrayAnalysisResult {
    fn default() -> Self {
        Self::new(String::new(), 0)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MediaArrayAnalysisResult {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "analysisText".to_string(),
            self.analysisText.to_baml_value()?,
        );
        map.insert("mediaCount".to_string(), self.mediaCount.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "MediaArrayAnalysisResult".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MediaArrayAnalysisResult {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let analysisText = map
                    .get("analysisText")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'analysisText' in MediaArrayAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let mediaCount = map
                    .get("mediaCount")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'mediaCount' in MediaArrayAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(analysisText, mediaCount))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MediaMapAnalysisResult {
    pub analysisText: String,

    pub keyCount: i64,

    pub keys: Vec<String>,
}

impl MediaMapAnalysisResult {
    /// Create a new MediaMapAnalysisResult instance
    pub fn new(analysisText: String, keyCount: i64, keys: Vec<String>) -> Self {
        Self {
            analysisText,
            keyCount,
            keys,
        }
    }
}

impl Default for MediaMapAnalysisResult {
    fn default() -> Self {
        Self::new(String::new(), 0, Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MediaMapAnalysisResult {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "analysisText".to_string(),
            self.analysisText.to_baml_value()?,
        );
        map.insert("keyCount".to_string(), self.keyCount.to_baml_value()?);
        map.insert("keys".to_string(), self.keys.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "MediaMapAnalysisResult".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MediaMapAnalysisResult {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let analysisText = map
                    .get("analysisText")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'analysisText' in MediaMapAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let keyCount = map
                    .get("keyCount")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'keyCount' in MediaMapAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let keys = map
                    .get("keys")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'keys' in MediaMapAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(analysisText, keyCount, keys))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MixedMediaAnalysisResult {
    pub title: String,

    pub description: String,

    pub hasImage: bool,

    pub hasVideo: bool,

    pub hasAudio: bool,

    pub hasPdf: bool,

    pub additionalImageCount: i64,

    pub metadataKeys: Vec<String>,
}

impl MixedMediaAnalysisResult {
    /// Create a new MixedMediaAnalysisResult instance
    pub fn new(
        title: String,
        description: String,
        hasImage: bool,
        hasVideo: bool,
        hasAudio: bool,
        hasPdf: bool,
        additionalImageCount: i64,
        metadataKeys: Vec<String>,
    ) -> Self {
        Self {
            title,
            description,
            hasImage,
            hasVideo,
            hasAudio,
            hasPdf,
            additionalImageCount,
            metadataKeys,
        }
    }
}

impl Default for MixedMediaAnalysisResult {
    fn default() -> Self {
        Self::new(
            String::new(),
            String::new(),
            false,
            false,
            false,
            false,
            0,
            Vec::new(),
        )
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedMediaAnalysisResult {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("title".to_string(), self.title.to_baml_value()?);
        map.insert("description".to_string(), self.description.to_baml_value()?);
        map.insert("hasImage".to_string(), self.hasImage.to_baml_value()?);
        map.insert("hasVideo".to_string(), self.hasVideo.to_baml_value()?);
        map.insert("hasAudio".to_string(), self.hasAudio.to_baml_value()?);
        map.insert("hasPdf".to_string(), self.hasPdf.to_baml_value()?);
        map.insert(
            "additionalImageCount".to_string(),
            self.additionalImageCount.to_baml_value()?,
        );
        map.insert(
            "metadataKeys".to_string(),
            self.metadataKeys.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedMediaAnalysisResult".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedMediaAnalysisResult {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let title = map
                    .get("title")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'title' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let description = map
                    .get("description")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'description' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let hasImage = map
                    .get("hasImage")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'hasImage' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let hasVideo = map
                    .get("hasVideo")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'hasVideo' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let hasAudio = map
                    .get("hasAudio")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'hasAudio' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let hasPdf = map
                    .get("hasPdf")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'hasPdf' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let additionalImageCount = map
                    .get("additionalImageCount")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'additionalImageCount' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let metadataKeys = map
                    .get("metadataKeys")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'metadataKeys' in MixedMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    title,
                    description,
                    hasImage,
                    hasVideo,
                    hasAudio,
                    hasPdf,
                    additionalImageCount,
                    metadataKeys,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OptionalMediaAnalysisResult {
    pub analysisText: String,

    pub providedMediaTypes: Vec<String>,

    pub missingMediaTypes: Vec<String>,
}

impl OptionalMediaAnalysisResult {
    /// Create a new OptionalMediaAnalysisResult instance
    pub fn new(
        analysisText: String,
        providedMediaTypes: Vec<String>,
        missingMediaTypes: Vec<String>,
    ) -> Self {
        Self {
            analysisText,
            providedMediaTypes,
            missingMediaTypes,
        }
    }
}

impl Default for OptionalMediaAnalysisResult {
    fn default() -> Self {
        Self::new(String::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for OptionalMediaAnalysisResult {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "analysisText".to_string(),
            self.analysisText.to_baml_value()?,
        );
        map.insert(
            "providedMediaTypes".to_string(),
            self.providedMediaTypes.to_baml_value()?,
        );
        map.insert(
            "missingMediaTypes".to_string(),
            self.missingMediaTypes.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "OptionalMediaAnalysisResult".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for OptionalMediaAnalysisResult {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let analysisText = map
                    .get("analysisText")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'analysisText' in OptionalMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let providedMediaTypes = map
                    .get("providedMediaTypes")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'providedMediaTypes' in OptionalMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let missingMediaTypes = map
                    .get("missingMediaTypes")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'missingMediaTypes' in OptionalMediaAnalysisResult"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    analysisText,
                    providedMediaTypes,
                    missingMediaTypes,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union4AudioOrImageOrPdfOrVideo {
    Media0(crate::typesBamlImage),
    Media1(crate::typesBamlAudio),
    Media2(crate::typesBamlPdf),
    Media3(crate::typesBamlVideo),
}

impl Union4AudioOrImageOrPdfOrVideo {
    /// Check if this union is a Media0 variant
    pub fn is_media0(&self) -> bool {
        matches!(self, Self::Media0(_))
    }
    /// Get the Media0 value if this union contains it
    pub fn as_media0(&self) -> Option<&crate::typesBamlImage> {
        match self {
            Self::Media0(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Media0 value, consuming the union
    pub fn into_media0(self) -> Option<crate::typesBamlImage> {
        match self {
            Self::Media0(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Media0 value if this union contains it
    pub fn as_media0_mut(&mut self) -> Option<&mut crate::typesBamlImage> {
        match self {
            Self::Media0(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4AudioOrImageOrPdfOrVideo with a Media0 variant
    pub fn media0(value: crate::typesBamlImage) -> Self {
        Self::Media0(value)
    }

    /// Check if this union is a Media1 variant
    pub fn is_media1(&self) -> bool {
        matches!(self, Self::Media1(_))
    }
    /// Get the Media1 value if this union contains it
    pub fn as_media1(&self) -> Option<&crate::typesBamlAudio> {
        match self {
            Self::Media1(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Media1 value, consuming the union
    pub fn into_media1(self) -> Option<crate::typesBamlAudio> {
        match self {
            Self::Media1(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Media1 value if this union contains it
    pub fn as_media1_mut(&mut self) -> Option<&mut crate::typesBamlAudio> {
        match self {
            Self::Media1(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4AudioOrImageOrPdfOrVideo with a Media1 variant
    pub fn media1(value: crate::typesBamlAudio) -> Self {
        Self::Media1(value)
    }

    /// Check if this union is a Media2 variant
    pub fn is_media2(&self) -> bool {
        matches!(self, Self::Media2(_))
    }
    /// Get the Media2 value if this union contains it
    pub fn as_media2(&self) -> Option<&crate::typesBamlPdf> {
        match self {
            Self::Media2(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Media2 value, consuming the union
    pub fn into_media2(self) -> Option<crate::typesBamlPdf> {
        match self {
            Self::Media2(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Media2 value if this union contains it
    pub fn as_media2_mut(&mut self) -> Option<&mut crate::typesBamlPdf> {
        match self {
            Self::Media2(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4AudioOrImageOrPdfOrVideo with a Media2 variant
    pub fn media2(value: crate::typesBamlPdf) -> Self {
        Self::Media2(value)
    }

    /// Check if this union is a Media3 variant
    pub fn is_media3(&self) -> bool {
        matches!(self, Self::Media3(_))
    }
    /// Get the Media3 value if this union contains it
    pub fn as_media3(&self) -> Option<&crate::typesBamlVideo> {
        match self {
            Self::Media3(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Media3 value, consuming the union
    pub fn into_media3(self) -> Option<crate::typesBamlVideo> {
        match self {
            Self::Media3(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Media3 value if this union contains it
    pub fn as_media3_mut(&mut self) -> Option<&mut crate::typesBamlVideo> {
        match self {
            Self::Media3(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4AudioOrImageOrPdfOrVideo with a Media3 variant
    pub fn media3(value: crate::typesBamlVideo) -> Self {
        Self::Media3(value)
    }
}

/// Pattern matching helper for Union4AudioOrImageOrPdfOrVideo
impl Union4AudioOrImageOrPdfOrVideo {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        media0: impl FnOnce(&crate::typesBamlImage) -> T,
        media1: impl FnOnce(&crate::typesBamlAudio) -> T,
        media2: impl FnOnce(&crate::typesBamlPdf) -> T,
        media3: impl FnOnce(&crate::typesBamlVideo) -> T,
    ) -> T {
        match self {
            Self::Media0(v) => media0(v),
            Self::Media1(v) => media1(v),
            Self::Media2(v) => media2(v),
            Self::Media3(v) => media3(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        media0: impl FnOnce(crate::typesBamlImage) -> T,
        media1: impl FnOnce(crate::typesBamlAudio) -> T,
        media2: impl FnOnce(crate::typesBamlPdf) -> T,
        media3: impl FnOnce(crate::typesBamlVideo) -> T,
    ) -> T {
        match self {
            Self::Media0(v) => media0(v),
            Self::Media1(v) => media1(v),
            Self::Media2(v) => media2(v),
            Self::Media3(v) => media3(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union4AudioOrImageOrPdfOrVideo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Media0(v) => write!(f, "Media0({:?})", v),
            Self::Media1(v) => write!(f, "Media1({:?})", v),
            Self::Media2(v) => write!(f, "Media2({:?})", v),
            Self::Media3(v) => write!(f, "Media3({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union4AudioOrImageOrPdfOrVideo {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::Media0(v) => v.to_baml_value(),
            Self::Media1(v) => v.to_baml_value(),
            Self::Media2(v) => v.to_baml_value(),
            Self::Media3(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union4AudioOrImageOrPdfOrVideo {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try Media0 variant
        if let Ok(variant_value) = crate::typesBamlImage::from_baml_value(value.clone()) {
            return Ok(Self::Media0(variant_value));
        }
        // Try Media1 variant
        if let Ok(variant_value) = crate::typesBamlAudio::from_baml_value(value.clone()) {
            return Ok(Self::Media1(variant_value));
        }
        // Try Media2 variant
        if let Ok(variant_value) = crate::typesBamlPdf::from_baml_value(value.clone()) {
            return Ok(Self::Media2(variant_value));
        }
        // Try Media3 variant
        if let Ok(variant_value) = crate::typesBamlVideo::from_baml_value(value.clone()) {
            return Ok(Self::Media3(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union4AudioOrImageOrPdfOrVideo",
            value
        )))
    }
}
