// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ cargo add baml-client
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ cargo install baml-cli

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArrayWithConstraints {
    pub nonEmptyStrings: Vec<String>,

    pub limitedInts: Vec<i64>,

    pub positiveFloats: Vec<f64>,
}

impl ArrayWithConstraints {
    /// Create a new ArrayWithConstraints instance
    pub fn new(
        nonEmptyStrings: Vec<String>,
        limitedInts: Vec<i64>,
        positiveFloats: Vec<f64>,
    ) -> Self {
        Self {
            nonEmptyStrings,
            limitedInts,
            positiveFloats,
        }
    }
}

impl Default for ArrayWithConstraints {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ArrayWithConstraints {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "nonEmptyStrings".to_string(),
            self.nonEmptyStrings.to_baml_value()?,
        );
        map.insert("limitedInts".to_string(), self.limitedInts.to_baml_value()?);
        map.insert(
            "positiveFloats".to_string(),
            self.positiveFloats.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "ArrayWithConstraints".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ArrayWithConstraints {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let nonEmptyStrings = map
                    .get("nonEmptyStrings")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nonEmptyStrings' in ArrayWithConstraints"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let limitedInts = map
                    .get("limitedInts")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'limitedInts' in ArrayWithConstraints"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let positiveFloats = map
                    .get("positiveFloats")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'positiveFloats' in ArrayWithConstraints"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(nonEmptyStrings, limitedInts, positiveFloats))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MixedArrays {
    pub primitiveArray: Vec<crate::typesUnion4BoolOrFloatOrIntOrString>,

    pub nullableArray: Vec<Option<String>>,

    pub optionalItems: Vec<Option<String>>,

    pub arrayOfArrays: Vec<Vec<String>>,

    pub complexMixed: Vec<crate::typesUnion3ProductOrTagOrUser>,
}

impl MixedArrays {
    /// Create a new MixedArrays instance
    pub fn new(
        primitiveArray: Vec<crate::typesUnion4BoolOrFloatOrIntOrString>,
        nullableArray: Vec<Option<String>>,
        optionalItems: Vec<Option<String>>,
        arrayOfArrays: Vec<Vec<String>>,
        complexMixed: Vec<crate::typesUnion3ProductOrTagOrUser>,
    ) -> Self {
        Self {
            primitiveArray,
            nullableArray,
            optionalItems,
            arrayOfArrays,
            complexMixed,
        }
    }
}

impl Default for MixedArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for MixedArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert(
            "primitiveArray".to_string(),
            self.primitiveArray.to_baml_value()?,
        );
        map.insert(
            "nullableArray".to_string(),
            self.nullableArray.to_baml_value()?,
        );
        map.insert(
            "optionalItems".to_string(),
            self.optionalItems.to_baml_value()?,
        );
        map.insert(
            "arrayOfArrays".to_string(),
            self.arrayOfArrays.to_baml_value()?,
        );
        map.insert(
            "complexMixed".to_string(),
            self.complexMixed.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "MixedArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for MixedArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let primitiveArray = map
                    .get("primitiveArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'primitiveArray' in MixedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let nullableArray = map
                    .get("nullableArray")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'nullableArray' in MixedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let optionalItems = map
                    .get("optionalItems")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'optionalItems' in MixedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let arrayOfArrays = map
                    .get("arrayOfArrays")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'arrayOfArrays' in MixedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let complexMixed = map
                    .get("complexMixed")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'complexMixed' in MixedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(
                    primitiveArray,
                    nullableArray,
                    optionalItems,
                    arrayOfArrays,
                    complexMixed,
                ))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct NestedArrays {
    pub matrix: Vec<Vec<i64>>,

    pub stringMatrix: Vec<Vec<String>>,

    pub threeDimensional: Vec<Vec<Vec<f64>>>,
}

impl NestedArrays {
    /// Create a new NestedArrays instance
    pub fn new(
        matrix: Vec<Vec<i64>>,
        stringMatrix: Vec<Vec<String>>,
        threeDimensional: Vec<Vec<Vec<f64>>>,
    ) -> Self {
        Self {
            matrix,
            stringMatrix,
            threeDimensional,
        }
    }
}

impl Default for NestedArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for NestedArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("matrix".to_string(), self.matrix.to_baml_value()?);
        map.insert(
            "stringMatrix".to_string(),
            self.stringMatrix.to_baml_value()?,
        );
        map.insert(
            "threeDimensional".to_string(),
            self.threeDimensional.to_baml_value()?,
        );
        Ok(baml_client_rust::types::BamlValue::Class(
            "NestedArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for NestedArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let matrix = map
                    .get("matrix")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'matrix' in NestedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let stringMatrix = map
                    .get("stringMatrix")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'stringMatrix' in NestedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let threeDimensional = map
                    .get("threeDimensional")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'threeDimensional' in NestedArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(matrix, stringMatrix, threeDimensional))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ObjectArrays {
    pub users: Vec<crate::typesUser>,

    pub products: Vec<crate::typesProduct>,

    pub tags: Vec<crate::typesTag>,
}

impl ObjectArrays {
    /// Create a new ObjectArrays instance
    pub fn new(
        users: Vec<crate::typesUser>,
        products: Vec<crate::typesProduct>,
        tags: Vec<crate::typesTag>,
    ) -> Self {
        Self {
            users,
            products,
            tags,
        }
    }
}

impl Default for ObjectArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for ObjectArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("users".to_string(), self.users.to_baml_value()?);
        map.insert("products".to_string(), self.products.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "ObjectArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for ObjectArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let users = map
                    .get("users")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'users' in ObjectArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let products = map
                    .get("products")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'products' in ObjectArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let tags = map
                    .get("tags")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in ObjectArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(users, products, tags))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Product {
    pub id: i64,

    pub name: String,

    pub price: f64,

    pub tags: Vec<String>,

    pub inStock: bool,
}

impl Product {
    /// Create a new Product instance
    pub fn new(id: i64, name: String, price: f64, tags: Vec<String>, inStock: bool) -> Self {
        Self {
            id,
            name,
            price,
            tags,
            inStock,
        }
    }
}

impl Default for Product {
    fn default() -> Self {
        Self::new(0, String::new(), 0.0, Vec::new(), false)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Product {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("price".to_string(), self.price.to_baml_value()?);
        map.insert("tags".to_string(), self.tags.to_baml_value()?);
        map.insert("inStock".to_string(), self.inStock.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Product".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Product {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let price = map
                    .get("price")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'price' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let tags = map
                    .get("tags")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'tags' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let inStock = map
                    .get("inStock")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'inStock' in Product"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, price, tags, inStock))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SimpleArrays {
    pub strings: Vec<String>,

    pub integers: Vec<i64>,

    pub floats: Vec<f64>,

    pub booleans: Vec<bool>,
}

impl SimpleArrays {
    /// Create a new SimpleArrays instance
    pub fn new(
        strings: Vec<String>,
        integers: Vec<i64>,
        floats: Vec<f64>,
        booleans: Vec<bool>,
    ) -> Self {
        Self {
            strings,
            integers,
            floats,
            booleans,
        }
    }
}

impl Default for SimpleArrays {
    fn default() -> Self {
        Self::new(Vec::new(), Vec::new(), Vec::new(), Vec::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for SimpleArrays {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("strings".to_string(), self.strings.to_baml_value()?);
        map.insert("integers".to_string(), self.integers.to_baml_value()?);
        map.insert("floats".to_string(), self.floats.to_baml_value()?);
        map.insert("booleans".to_string(), self.booleans.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "SimpleArrays".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for SimpleArrays {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let strings = map
                    .get("strings")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'strings' in SimpleArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let integers = map
                    .get("integers")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'integers' in SimpleArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let floats = map
                    .get("floats")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'floats' in SimpleArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let booleans = map
                    .get("booleans")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'booleans' in SimpleArrays"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(strings, integers, floats, booleans))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Tag {
    pub id: i64,

    pub name: String,

    pub color: String,
}

impl Tag {
    /// Create a new Tag instance
    pub fn new(id: i64, name: String, color: String) -> Self {
        Self { id, name, color }
    }
}

impl Default for Tag {
    fn default() -> Self {
        Self::new(0, String::new(), String::new())
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Tag {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("color".to_string(), self.color.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "Tag".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for Tag {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in Tag"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in Tag"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let color = map
                    .get("color")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'color' in Tag"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, color))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct User {
    pub id: i64,

    pub name: String,

    pub email: String,

    pub isActive: bool,
}

impl User {
    /// Create a new User instance
    pub fn new(id: i64, name: String, email: String, isActive: bool) -> Self {
        Self {
            id,
            name,
            email,
            isActive,
        }
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new(0, String::new(), String::new(), false)
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for User {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        let mut map = baml_client_rust::types::BamlMap::new();
        map.insert("id".to_string(), self.id.to_baml_value()?);
        map.insert("name".to_string(), self.name.to_baml_value()?);
        map.insert("email".to_string(), self.email.to_baml_value()?);
        map.insert("isActive".to_string(), self.isActive.to_baml_value()?);
        Ok(baml_client_rust::types::BamlValue::Class(
            "User".to_string(),
            map,
        ))
    }
}

impl baml_client_rust::types::FromBamlValue for User {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        match value {
            baml_client_rust::types::BamlValue::Class(_class_name, map) => {
                let id = map
                    .get("id")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'id' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let name = map
                    .get("name")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'name' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let email = map
                    .get("email")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'email' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                let isActive = map
                    .get("isActive")
                    .ok_or_else(|| {
                        baml_client_rust::BamlError::deserialization(format!(
                            "Missing field 'isActive' in User"
                        ))
                    })
                    .and_then(|v| {
                        baml_client_rust::types::FromBamlValue::from_baml_value(v.clone())
                    })?;
                Ok(Self::new(id, name, email, isActive))
            }
            _ => Err(baml_client_rust::BamlError::deserialization(format!(
                "Expected class, got {:?}",
                value
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3BoolOrIntOrString {
    String(String),
    Int(i64),
    Bool(bool),
}

impl Union3BoolOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3BoolOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union3BoolOrIntOrString
impl Union3BoolOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3BoolOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union3BoolOrIntOrString {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::String(v) => v.to_baml_value(),
            Self::Int(v) => v.to_baml_value(),
            Self::Bool(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union3BoolOrIntOrString {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try String variant
        if let Ok(variant_value) = String::from_baml_value(value.clone()) {
            return Ok(Self::String(variant_value));
        }
        // Try Int variant
        if let Ok(variant_value) = i64::from_baml_value(value.clone()) {
            return Ok(Self::Int(variant_value));
        }
        // Try Bool variant
        if let Ok(variant_value) = bool::from_baml_value(value.clone()) {
            return Ok(Self::Bool(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union3BoolOrIntOrString",
            value
        )))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union3ProductOrTagOrUser {
    User(crate::typesUser),
    Product(crate::typesProduct),
    Tag(crate::typesTag),
}

impl Union3ProductOrTagOrUser {
    /// Check if this union is a User variant
    pub fn is_user(&self) -> bool {
        matches!(self, Self::User(_))
    }
    /// Get the User value if this union contains it
    pub fn as_user(&self) -> Option<&crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the User value, consuming the union
    pub fn into_user(self) -> Option<crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the User value if this union contains it
    pub fn as_user_mut(&mut self) -> Option<&mut crate::typesUser> {
        match self {
            Self::User(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a User variant
    pub fn user(value: crate::typesUser) -> Self {
        Self::User(value)
    }

    /// Check if this union is a Product variant
    pub fn is_product(&self) -> bool {
        matches!(self, Self::Product(_))
    }
    /// Get the Product value if this union contains it
    pub fn as_product(&self) -> Option<&crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Product value, consuming the union
    pub fn into_product(self) -> Option<crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Product value if this union contains it
    pub fn as_product_mut(&mut self) -> Option<&mut crate::typesProduct> {
        match self {
            Self::Product(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a Product variant
    pub fn product(value: crate::typesProduct) -> Self {
        Self::Product(value)
    }

    /// Check if this union is a Tag variant
    pub fn is_tag(&self) -> bool {
        matches!(self, Self::Tag(_))
    }
    /// Get the Tag value if this union contains it
    pub fn as_tag(&self) -> Option<&crate::typesTag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Tag value, consuming the union
    pub fn into_tag(self) -> Option<crate::typesTag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Tag value if this union contains it
    pub fn as_tag_mut(&mut self) -> Option<&mut crate::typesTag> {
        match self {
            Self::Tag(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union3ProductOrTagOrUser with a Tag variant
    pub fn tag(value: crate::typesTag) -> Self {
        Self::Tag(value)
    }
}

/// Pattern matching helper for Union3ProductOrTagOrUser
impl Union3ProductOrTagOrUser {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        user: impl FnOnce(&crate::typesUser) -> T,
        product: impl FnOnce(&crate::typesProduct) -> T,
        tag: impl FnOnce(&crate::typesTag) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
            Self::Tag(v) => tag(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        user: impl FnOnce(crate::typesUser) -> T,
        product: impl FnOnce(crate::typesProduct) -> T,
        tag: impl FnOnce(crate::typesTag) -> T,
    ) -> T {
        match self {
            Self::User(v) => user(v),
            Self::Product(v) => product(v),
            Self::Tag(v) => tag(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union3ProductOrTagOrUser {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::User(v) => write!(f, "User({:?})", v),
            Self::Product(v) => write!(f, "Product({:?})", v),
            Self::Tag(v) => write!(f, "Tag({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union3ProductOrTagOrUser {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::User(v) => v.to_baml_value(),
            Self::Product(v) => v.to_baml_value(),
            Self::Tag(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union3ProductOrTagOrUser {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try User variant
        if let Ok(variant_value) = crate::typesUser::from_baml_value(value.clone()) {
            return Ok(Self::User(variant_value));
        }
        // Try Product variant
        if let Ok(variant_value) = crate::typesProduct::from_baml_value(value.clone()) {
            return Ok(Self::Product(variant_value));
        }
        // Try Tag variant
        if let Ok(variant_value) = crate::typesTag::from_baml_value(value.clone()) {
            return Ok(Self::Tag(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union3ProductOrTagOrUser",
            value
        )))
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Union4BoolOrFloatOrIntOrString {
    String(String),
    Int(i64),
    Float(f64),
    Bool(bool),
}

impl Union4BoolOrFloatOrIntOrString {
    /// Check if this union is a String variant
    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }
    /// Get the String value if this union contains it
    pub fn as_string(&self) -> Option<&String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the String value, consuming the union
    pub fn into_string(self) -> Option<String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the String value if this union contains it
    pub fn as_string_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::String(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a String variant
    pub fn string(value: String) -> Self {
        Self::String(value)
    }

    /// Check if this union is a Int variant
    pub fn is_int(&self) -> bool {
        matches!(self, Self::Int(_))
    }
    /// Get the Int value if this union contains it
    pub fn as_int(&self) -> Option<&i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Int value, consuming the union
    pub fn into_int(self) -> Option<i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Int value if this union contains it
    pub fn as_int_mut(&mut self) -> Option<&mut i64> {
        match self {
            Self::Int(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Int variant
    pub fn int(value: i64) -> Self {
        Self::Int(value)
    }

    /// Check if this union is a Float variant
    pub fn is_float(&self) -> bool {
        matches!(self, Self::Float(_))
    }
    /// Get the Float value if this union contains it
    pub fn as_float(&self) -> Option<&f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Float value, consuming the union
    pub fn into_float(self) -> Option<f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Float value if this union contains it
    pub fn as_float_mut(&mut self) -> Option<&mut f64> {
        match self {
            Self::Float(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Float variant
    pub fn float(value: f64) -> Self {
        Self::Float(value)
    }

    /// Check if this union is a Bool variant
    pub fn is_bool(&self) -> bool {
        matches!(self, Self::Bool(_))
    }
    /// Get the Bool value if this union contains it
    pub fn as_bool(&self) -> Option<&bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Extract the Bool value, consuming the union
    pub fn into_bool(self) -> Option<bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Get a mutable reference to the Bool value if this union contains it
    pub fn as_bool_mut(&mut self) -> Option<&mut bool> {
        match self {
            Self::Bool(v) => Some(v),
            _ => None,
        }
    }

    /// Create a new Union4BoolOrFloatOrIntOrString with a Bool variant
    pub fn bool(value: bool) -> Self {
        Self::Bool(value)
    }
}

/// Pattern matching helper for Union4BoolOrFloatOrIntOrString
impl Union4BoolOrFloatOrIntOrString {
    /// Match on the union variant and apply the corresponding function
    pub fn match_variant<T>(
        &self,
        string: impl FnOnce(&String) -> T,
        int: impl FnOnce(&i64) -> T,
        float: impl FnOnce(&f64) -> T,
        bool: impl FnOnce(&bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Bool(v) => bool(v),
        }
    }

    /// Match on the union variant and apply the corresponding function, consuming the union
    pub fn match_variant_owned<T>(
        self,
        string: impl FnOnce(String) -> T,
        int: impl FnOnce(i64) -> T,
        float: impl FnOnce(f64) -> T,
        bool: impl FnOnce(bool) -> T,
    ) -> T {
        match self {
            Self::String(v) => string(v),
            Self::Int(v) => int(v),
            Self::Float(v) => float(v),
            Self::Bool(v) => bool(v),
        }
    }
}

/// Display implementation that shows the variant name and value
impl std::fmt::Display for Union4BoolOrFloatOrIntOrString {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::String(v) => write!(f, "String({:?})", v),
            Self::Int(v) => write!(f, "Int({:?})", v),
            Self::Float(v) => write!(f, "Float({:?})", v),
            Self::Bool(v) => write!(f, "Bool({:?})", v),
        }
    }
}

// BAML trait implementations
impl baml_client_rust::types::ToBamlValue for Union4BoolOrFloatOrIntOrString {
    fn to_baml_value(self) -> baml_client_rust::BamlResult<baml_client_rust::types::BamlValue> {
        match self {
            Self::String(v) => v.to_baml_value(),
            Self::Int(v) => v.to_baml_value(),
            Self::Float(v) => v.to_baml_value(),
            Self::Bool(v) => v.to_baml_value(),
        }
    }
}

impl baml_client_rust::types::FromBamlValue for Union4BoolOrFloatOrIntOrString {
    fn from_baml_value(
        value: baml_client_rust::types::BamlValue,
    ) -> baml_client_rust::BamlResult<Self> {
        // Try String variant
        if let Ok(variant_value) = String::from_baml_value(value.clone()) {
            return Ok(Self::String(variant_value));
        }
        // Try Int variant
        if let Ok(variant_value) = i64::from_baml_value(value.clone()) {
            return Ok(Self::Int(variant_value));
        }
        // Try Float variant
        if let Ok(variant_value) = f64::from_baml_value(value.clone()) {
            return Ok(Self::Float(variant_value));
        }
        // Try Bool variant
        if let Ok(variant_value) = bool::from_baml_value(value.clone()) {
            return Ok(Self::Bool(variant_value));
        }

        Err(baml_client_rust::BamlError::deserialization(format!(
            "Could not convert {:?} to Union4BoolOrFloatOrIntOrString",
            value
        )))
    }
}
